from pathlib import Path
import re
p=Path('rapport/rapport-bagages.tex');s=p.read_text(encoding='utf-8');figs={}
for m in re.finditer(r'\\begin\{figure\}\[H\].*?\\end\{figure\}',s,re.S):
 text=m.group();label=re.search(r'\\label\{([^}]+)\}',text)
 if label and label.group(1).startswith('fig:phase-') or label and label.group(1).startswith('fig:recette-'):
  figs[label.group(1)]=text
print('Captures disponibles',len(figs))
start=s.index(r'\chaptertitle{Chapitre 3');end=s.index(r'\fronttitle{Conclusion générale}',start)
old=s[start:end]
result=old[old.index(r'\begin{table}[htbp]\centering\caption{Contrôles OVH'):old.index(r'\subsection{Validations Internet}')]
requirements=re.search(r'\\begin\{longtable\}\{p\{4\.2cm\}.*?\\end\{longtable\}',old,re.S).group()
parts=[r'\chaptertitle{Chapitre 3 : Réalisation, tests et validation}{3}',r'\subsection{Introduction}',"La réalisation a été conduite progressivement : construire d’abord une API reliée à PostgreSQL, développer les parcours Angular, protéger les services privés, puis déployer la solution sur Kubernetes et sur un VPS. À chaque étape, les observations ont orienté le travail suivant. Les captures sont insérées au moment où elles éclairent une décision ou un résultat ; elles ne constituent pas une suite indépendante de la démarche.",r'\subsection{Préparation de l’environnement}',"Le poste Windows accueille les sources, Docker Desktop et les outils de validation. La pile retenue associe .NET 8, Entity Framework Core, PostgreSQL 16 et Angular 22. La virtualisation VMware permet ensuite de vérifier la solution depuis Ubuntu. Les comptes, vols et passagers utilisés sont fictifs. Les résultats présentés sont ceux enregistrés les 1er et 2 octobre 2026."]
used=[]
def section(title):parts.append(r'\subsection{'+title+'}')
def step(title,text,labels,after):
 parts.extend([r'\subsubsection{'+title+'}',text])
 for label in labels:parts.append(figs[label]);used.append(label)
 parts.append(after)
def labels(phase,*nums):return ['fig:'+phase+'-'+str(n) for n in nums]
section('Fondations : construire et vérifier la chaîne API--base de données')
step('Modélisation et premier démarrage',"La première étape consiste à créer les tables des comptes, rôles, vols, bagages et événements. Les migrations rendent cette structure reproductible. Une fois la connexion PostgreSQL configurée, l’API est démarrée en environnement local ; Swagger donne une vue de son contrat et permet de contrôler les réponses du serveur.",labels('phase-01',1,2),"La liste des routes permet de repérer les fonctions disponibles, tandis que la réponse 200 de la sonde de disponibilité confirme la connexion à PostgreSQL. Ces deux observations valident le point de départ technique ; elles ne démontrent pas encore la sécurité des opérations.")
step('Distinguer lecture publique et opérations authentifiées',"Le suivi passager doit fonctionner sans compte, mais la consultation des vols relève des opérations internes. Cette différence est vérifiée directement dans l’API : un appel aux vols sans jeton est refusé, puis le code fictif de suivi permet de lire un parcours déjà enregistré.",labels('phase-01',3,4),"Le refus 401 est le résultat attendu de l’authentification applicative. La réponse de suivi présente le statut et les événements sans révéler l’identité du passager. La séparation fonctionnelle est donc établie avant l’ajout du VPN.")
step('Rendre l’exécution reproductible avec Docker',"L’API et PostgreSQL sont ensuite exécutés dans des conteneurs pour stabiliser leur environnement. Docker Desktop permet d’observer les deux services. La sonde de vie et le suivi sont rejoués sur l’API conteneurisée afin de vérifier que le changement d’environnement conserve le fonctionnement métier.",labels('phase-01',5,6,7),"Les réponses restent cohérentes avec l’exécution native. Le port local 18080 appartient à cette étape de développement ; les phases suivantes retireront la publication directe de l’API. La chaîne de données étant opérationnelle, le travail peut se poursuivre sur les interfaces utilisateur.")
section('Interfaces Angular : réaliser un parcours métier complet')
step('Préparer les accès public et agents',"Deux applications Angular sont compilées séparément. L’accueil public propose uniquement la recherche par code. L’espace agents possède une navigation privée ; lorsque la page des bagages est demandée sans session, la garde conduit vers la connexion. Cette séparation rend visibles les deux usages dès l’entrée dans l’application.",labels('phase-02',1,3),"Le passager n’a pas à s’authentifier pour utiliser son code. L’agent doit ouvrir une session avant les fonctions internes. Cette protection de navigation accompagne les contrôles de l’API ; elle ne les remplace pas.")
step('Organiser le travail du superviseur',"Le superviseur dispose d’une vue métier des bagages et des vols. Les indicateurs du tableau de bord sont calculés à partir des listes chargées et sont présentés avec leurs limites. Ce rôle prépare le contexte de l’enregistrement et ne donne pas automatiquement accès à la gestion des comptes.",labels('phase-02',4),"La capture montre les menus métier accessibles au superviseur et l’absence du menu comptes. La distinction des responsabilités est ainsi visible dans l’interface avant d’être contrôlée lors des appels API.")
step('Enregistrer le bagage puis effectuer le tri',"Après création du vol, l’agent d’enregistrement sélectionne ce vol et saisit les données fictives du bagage. La création produit un reçu et un code de suivi. L’agent de tri retrouve ensuite le bagage et demande le passage à l’étape Trié ; l’API contrôle la transition et ajoute l’événement associé.",labels('phase-02',6,7),"Le reçu relie l’opération interne au suivi passager. L’historique de tri montre que le statut n’est pas une simple modification d’affichage : il correspond à une transition conservée en base. Le passager peut maintenant consulter ce parcours.")
step('Vérifier la continuité avec le suivi passager',"Le code obtenu lors de l’enregistrement est saisi dans l’application publique. La consultation restitue l’état Trié et les horodatages du parcours. Les données viennent de la même API et de la même base que celles utilisées par les agents.",labels('phase-02',2),"Cette étape ferme la boucle entre enregistrement, manutention et information du passager. La capture reflète l’état du bagage au moment de la consultation ; une correction ultérieure peut modifier ce statut sans invalider la trace historique de cette étape.")
step('Conserver la trace des corrections exceptionnelles',"Une transition qui sort du parcours normal demande l’intervention du superviseur et un motif. Le scénario de correction vers Livré vérifie que l’application conserve la justification et l’agent responsable, au lieu de masquer l’anomalie par un changement silencieux.",labels('phase-02',5),"L’événement marqué comme exceptionnel permet de comprendre la correction. La traçabilité reste donc exploitable même lorsque le cycle normal n’a pas été suivi intégralement.")
step('Isoler l’administration et contrôler l’origine de l’interface',"Le compte administrateur est réservé à la gestion des utilisateurs. Une création de compte fictif est réalisée depuis son formulaire. L’application agents vérifie aussi son origine de service : une origine locale absente de la liste autorisée empêche le chargement du module.",labels('phase-02',8,9),"La confirmation de création ne révèle pas le mot de passe. Le refus d’origine constitue un contrôle applicatif supplémentaire, distinct du VPN. Les parcours ayant été vérifiés, la réalisation aborde maintenant la protection réseau nécessaire aux opérations privées.")
section('Sécurisation réseau : ajouter le VPN aux autorisations applicatives')
step('Segmenter les conteneurs et limiter les publications',"Les composants sont répartis sur des réseaux dédiés au point d’entrée, aux échanges avec l’API et à PostgreSQL. Nginx public relaie uniquement le suivi ; le proxy agents reste sur le chemin privé. WireGuard ajoute la passerelle nécessaire aux clients habilités. La vue Docker Desktop permet de vérifier l’organisation obtenue.",labels('phase-03',1),"La présence des services ne signifie pas que leurs ports sont accessibles à tous. Les fonctions privées ne sont plus publiées comme dans le laboratoire initial. Il reste à vérifier cette frontière depuis des clients placés avec et sans tunnel.")
step('Tester le tunnel avec le même jeton',"Un client autorisé établit le tunnel puis utilise un JWT valide pour atteindre le service privé. Le tunnel est coupé en conservant ce jeton, puis rétabli. Un second client, extérieur au VPN dans le laboratoire Docker, essaie les mêmes accès et consulte le suivi public.",labels('phase-03',2,3),"L’accès privé disparaît à la coupure et revient avec le tunnel, tandis que le site public reste disponible. Ce résultat montre que le JWT ne suffit pas à franchir la frontière réseau. À cette étape, les clients sont encore des conteneurs sur le même poste : la validation porte sur le laboratoire, avant son transfert vers Kubernetes.")
section('Kubernetes : déployer les composants et vérifier la persistance')
step('Installer le cluster et déclarer les ressources',"Un cluster k3s mono-nœud est créé dans k3d. L’API et les interfaces utilisent des Deployments ; PostgreSQL utilise un StatefulSet et un volume persistant. Les migrations et l’initialisation passent par des Jobs. Les sorties kubectl enregistrées complètent la vue du nœud dans Docker Desktop.",labels('phase-04',1,4),"Le lecteur de sorties kubectl visible dans Docker sert uniquement à consulter les preuves. Les services privés sont déclarés en ClusterIP, les flux sont limités par NetworkPolicy et le stockage reste local au nœud. Le déploiement doit ensuite être vérifié depuis ses points d’entrée.")
step('Retrouver les protections réseau et conserver les données',"Les essais avec et sans VPN sont reproduits contre Kubernetes. La validation contrôle également les politiques réseau et le remplacement du pod PostgreSQL. Après ce remplacement, le bagage et ses événements doivent rester disponibles grâce au volume persistant.",labels('phase-04',2,3),"La frontière VPN est conservée après le changement de mode de déploiement. La persistance vérifiée concerne le remplacement du pod ; elle ne prouve pas une reprise après perte du disque. Une restauration de sauvegarde sera donc testée séparément.")
step('Sortir du client Docker : Windows et Ubuntu VMware',"Le client WireGuard natif de Windows est utilisé pour vérifier le chemin réel du poste vers le service privé. Une VM Ubuntu exécute ensuite la même famille de contrôles. Les résultats de ces systèmes sont archivés puis consultés dans Docker Desktop, qui joue ici le rôle de lecteur et non celui de client testé.",labels('phase-04',5,6),"Ces essais confirment le fonctionnement depuis Windows et un système invité Ubuntu. La VM reste sur le même poste physique : son utilisation ne suffit pas, à elle seule, à conclure à un accès VPN depuis Internet.")
step('Préparer une VM dédiée aux validations',"Une nouvelle VM est installée depuis l’ISO Ubuntu fourni, sur un disque distinct. Son premier démarrage confirme l’installation. Les tests réseau et VPN sont ensuite exécutés dans sa console, puis complétés par la consultation HTTPS du service public via une URL temporaire.",labels('phase-04d',1,2,3),"La VM dédiée fournit un client de laboratoire reproductible. Les tests de tunnel local et les contrôles HTTPS publics sont distingués : seuls ces derniers empruntent l’URL Internet temporaire. La suite du travail examine séparément la fermeture des ports locaux et le tunnel Internet.")
step('Vérifier les ports du poste partagé',"Les services Windows étrangers au projet sont liés à localhost afin de ne plus les exposer sur le LAN. Depuis la seconde VM, les ports concernés sont contrôlés, puis les accès par VPN local et les restrictions du site public sont vérifiés.",labels('phase-04e',2),"Les contrôles présentés valident le LAN et le VPN local. Leur portée reste distincte d’un handshake WireGuard par Internet, qui demande un point d’entrée accessible depuis un réseau extérieur.")
section('Recette et premier accès Internet')
step('Consulter le suivi par HTTPS et vérifier la restauration',"Un relais HTTPS temporaire permet de consulter le suivi public depuis Internet. Le bagage fictif apparaît avec ses événements. En parallèle, un dump PostgreSQL est restauré dans une base temporaire indépendante ; les cinq tables, leurs empreintes et les droits de l’historique sont comparés.",labels('recette',1,2),"La consultation confirme la continuité du suivi au travers du relais. La restauration logique vérifie l’utilisabilité de la sauvegarde sans remplacer la base active. L’URL temporaire est arrêtée après les essais ; elle ne constitue pas l’hébergement final.")
step('Valider WireGuard au travers d’un relais UDP public',"Un relais UDP temporaire fournit ensuite un chemin Internet vers WireGuard. La VM réalise le handshake, utilise le JWT, coupe le tunnel et le rétablit. Les contrôles complémentaires vérifient le refus d’un pair inconnu et les restrictions des routes publiques.",labels('phase-04f',1,2),"Ces observations constituent une première validation Internet du tunnel, dans le périmètre du relais. Les services partagés du fournisseur ne sont pas scannés et le relais est arrêté après utilisation. Pour la soutenance, ce mécanisme temporaire est remplacé par un VPS disposant de son propre point d’entrée.")
section('Hébergement OVH : rendre la démonstration indépendante du poste')
step('Publier le service passager avec un certificat reconnu',"Le déploiement est transféré vers le VPS Ubuntu 24.04. Le point d’entrée HTTPS public utilise un certificat Let’s Encrypt reconnu et sert l’application Angular. Le parcours de suivi est repris avec un bagage fictif pour vérifier que les réponses proviennent désormais du serveur distant.",labels('phase-05',1,2),"Le site public est disponible tant que le VPS et son abonnement restent actifs, même lorsque le poste local est éteint. Le statut Trié et les deux événements sont conservés sur OVH ; aucune identité du passager n’est affichée.")
step('Contrôler la frontière privée depuis Internet',"WireGuard écoute directement sur UDP 52820 du VPS. La VM vérifie l’inaccessibilité des fonctions privées sans VPN et les huit ports TCP sensibles documentés. Sur Windows, le tunnel autorisé permet ensuite de charger l’interface agents en HTTPS avec son certificat privé reconnu.",labels('phase-05',3,4),"La page de connexion montre le chargement réel de l’interface privée, sans prétendre représenter une session métier déjà ouverte. Les scénarios API complètent cette observation : refus sans jeton, refus d’un pair inconnu, coupure et rétablissement avec le même JWT. Les vérifications IPv4 et IPv6 portent sur les routes et ports documentés, sans revendiquer un scan exhaustif.")
step('Assurer la maintenance et vérifier la reprise',"L’administration SSH utilise une clé ; les mots de passe SSH sont désactivés après validation de cet accès. Le renouvellement du certificat public est simulé et son hook met à jour le secret TLS. PostgreSQL fournit pg\\_dump pour les sauvegardes logiques : un dump quotidien est planifié à 02:15 UTC et les sept dernières sauvegardes réussies sont conservées.",[],"Une copie manuelle hors VPS possède la même empreinte que le dump serveur. La restauration est vérifiée dans une base distincte. Enfin, un redémarrage réel du VPS remet les quatre pods applicatifs en état prêt et conserve les trois bagages de démonstration. Ces résultats vérifient la reprise après redémarrage, pas la haute disponibilité ni la perte complète du nœud.")
section('Bilan de validation et correspondance avec le cahier des charges')
parts.append('La validation associe appels HTTP, parcours métier, accès réseau et observations dans les interfaces. Les rejeux ne sont pas comptés deux fois. Le bilan OVH rassemble les contrôles suivants, exécutés après le déploiement distant.')
parts.append(result);parts.append(requirements)
parts += [r'\subsection{Limites et perspectives}',"La réalisation constitue un démonstrateur mono-nœud. La copie hors VPS reste manuelle, les alertes continues ne sont pas validées et la perte complète du disque n’a pas été simulée. Une exploitation réelle demanderait une stratégie de haute disponibilité, de sauvegarde hors site automatisée, de supervision et de gestion des mises à jour.",r'\subsection{Conclusion du chapitre}',"La progression part d’une chaîne API--base fonctionnelle, la rend utilisable par les différents rôles, puis ajoute les frontières réseau et la persistance. Les clients Windows et VMware élargissent la validation ; le VPS termine la démarche en fournissant un hébergement Internet direct. Chaque série de captures intervient ainsi dans l’explication du résultat qui permet de passer à l’étape suivante."]
assert len(used)==37 and set(used)==set(figs),(len(used),len(figs))
s=s[:start]+'\n\n'.join(parts)+'\n'+s[end:]
s=s.replace('PostgreSQL fournit pg\\_dump','PostgreSQL~\\cite{postgresql} fournit \\texttt{pg\\_dump}')
p.write_text(s,encoding='utf-8',newline='\n');print('Chapitre 3 réécrit ; 37 captures intégrées dans les étapes métier et techniques.')