// <auto-generated />
using System;
using Bagage.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagage.Api.Migrations
{
    [DbContext(typeof(BagageDb))]
    [Migration("20260930235636_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bagage.Api.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EchecsConnexion")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("VerrouilleJusqua")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bagage.Api.BagageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomPassager")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PoidsKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackingId")
                        .IsUnique();

                    b.HasIndex("VolId", "Statut");

                    b.ToTable("bagages", null, t =>
                        {
                            t.HasCheckConstraint("ck_bagages_poids", "\"PoidsKg\" > 0 AND \"PoidsKg\" <= 100");

                            t.HasCheckConstraint("ck_bagages_statut", "\"Statut\" IN ('enregistre','trie','charge','en_vol','livre','perdu')");
                        });
                });

            modelBuilder.Entity("Bagage.Api.HistoriqueStatut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AncienStatut")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Anomalie")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BagageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Horodatage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motif")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NouveauStatut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BagageId", "Horodatage");

                    b.ToTable("historique_statuts", (string)null);
                });

            modelBuilder.Entity("Bagage.Api.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "AgentEnregistrement"
                        },
                        new
                        {
                            Name = "AgentTri"
                        },
                        new
                        {
                            Name = "Superviseur"
                        },
                        new
                        {
                            Name = "Administrateur"
                        });
                });

            modelBuilder.Entity("Bagage.Api.Vol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DepartPrevu")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("Numero", "DepartPrevu")
                        .IsUnique();

                    b.ToTable("vols", (string)null);
                });

            modelBuilder.Entity("Bagage.Api.Agent", b =>
                {
                    b.HasOne("Bagage.Api.Role", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bagage.Api.BagageRecord", b =>
                {
                    b.HasOne("Bagage.Api.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("VolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("Bagage.Api.HistoriqueStatut", b =>
                {
                    b.HasOne("Bagage.Api.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bagage.Api.BagageRecord", null)
                        .WithMany()
                        .HasForeignKey("BagageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
