import { Component, signal, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { HttpClient, HttpParams } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { Bag, Flight, Status, statuses, statusLabels, errorText } from '../../shared/models';
import { Auth } from './auth';
import { BagHistory } from './history';

@Component({ imports:[FormsModule,DatePipe,BagHistory],template:`
<div class="page-heading"><span class="eyebrow">SUIVI OPÉRATIONNEL</span><h1>Bagages</h1><p class="muted">Consultez les parcours et enregistrez chaque nouvelle étape.</p></div>
<section class="panel"><form class="filters" (ngSubmit)="filter()"><div><label for="flight-filter">Vol</label><select id="flight-filter" name="vol" [(ngModel)]="volId"><option value="">Tous les vols</option>@for(v of flights();track v.id){<option [value]="v.id">{{v.numero}} · {{v.origine}} → {{v.destination}}</option>}</select></div><div><label for="status-filter">Statut</label><select id="status-filter" name="statut" [(ngModel)]="statut"><option value="">Tous les statuts</option>@for(s of statuses;track s){<option [value]="s">{{labels[s]}}</option>}</select></div><button class="btn" [disabled]="busy()">Appliquer les filtres</button></form>
@if(error()){<div class="alert" role="alert">{{error()}}</div>}
@if(busy()){<p role="status">Chargement des bagages…</p>}
<div class="table-wrap"><table><thead><tr><th>Référence de suivi</th><th>Vol</th><th>Statut</th><th>Poids</th><th>Enregistré le</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>@for(b of bags();track b.id){<tr><td class="mono" [title]="b.trackingId">{{b.trackingId.slice(0,12)}}…</td><td>{{flightName(b.volId)}}</td><td><span [class]="'badge '+b.statut">{{labels[b.statut]}}</span></td><td>{{b.poidsKg}} kg</td><td>{{b.creeLe | date:'dd/MM HH:mm'}}</td><td><button (click)="select(b)" [attr.aria-label]="'Ouvrir le bagage '+b.trackingId.slice(0,12)">Ouvrir →</button></td></tr>}</tbody></table></div>@if(!busy()&&!bags().length){<p class="empty">Aucun bagage ne correspond à ces filtres.</p>}<div class="pagination"><span>Page {{page}} · {{bags().length}} résultat(s), 50 maximum par page</span><div><button class="btn ghost" [disabled]="page===1||busy()" (click)="changePage(-1)">Précédente</button><button class="btn ghost" [disabled]="bags().length<50||busy()" (click)="changePage(1)">Suivante</button></div></div></section>
@if(selected();as bag){<section class="bag-detail stack" aria-label="Détail du bagage"><div class="panel"><div class="topline"><h2>Mettre à jour le parcours</h2><button class="btn ghost" (click)="selected.set(null)">Fermer</button></div><p class="mono small">{{bag.trackingId}}</p><p>Statut actuel : <span [class]="'badge '+bag.statut">{{labels[bag.statut]}}</span></p><form class="stack" (ngSubmit)="update()"><div><label for="next-status">Nouveau statut</label><select id="next-status" name="next" [(ngModel)]="nextStatus" required><option value="" disabled>Choisir une étape</option>@for(s of allowed(bag.statut);track s){<option [value]="s">{{labels[s]}}</option>}</select></div>@if(auth.has('Superviseur')){<div><label for="reason">Motif de correction</label><textarea id="reason" name="motif" [(ngModel)]="motif" maxlength="500" rows="2" [required]="isAbnormal(bag.statut)"></textarea><small class="muted">Obligatoire pour une transition hors parcours normal.</small></div>}@if(updateError()){<div class="alert" role="alert">{{updateError()}}</div>}@if(message()){<div class="alert success" role="status">{{message()}}</div>}<button class="btn" [disabled]="saving()||!nextStatus">{{saving()?'Enregistrement…':'Enregistrer le statut'}}</button></form></div><bag-history [bagId]="bag.id" [revision]="revision()" /></section>}` })
export class BagsPage {
  auth=inject(Auth); private http=inject(HttpClient); bags=signal<Bag[]>([]);flights=signal<Flight[]>([]);selected=signal<Bag|null>(null);busy=signal(false);saving=signal(false);error=signal('');updateError=signal('');message=signal('');revision=signal(0);labels=statusLabels;statuses=statuses;volId='';statut='';page=1;nextStatus='';motif='';
  constructor(){void this.init();}
  async init(){try{this.flights.set(await firstValueFrom(this.http.get<Flight[]>('/api/vols')));}catch(e){this.error.set(errorText(e));return;}await this.load();}
  flightName(id:string){return this.flights().find(v=>v.id===id)?.numero ?? 'Vol archivé';}
  filter(){this.page=1;this.selected.set(null);void this.load();}changePage(delta:number){this.page+=delta;this.selected.set(null);void this.load();}
  async load(){this.busy.set(true);this.error.set('');let params=new HttpParams().set('page',this.page);if(this.volId)params=params.set('volId',this.volId);if(this.statut)params=params.set('statut',this.statut);try{this.bags.set(await firstValueFrom(this.http.get<Bag[]>('/api/bagages',{params})));}catch(e){this.error.set(errorText(e));this.bags.set([]);}finally{this.busy.set(false);}}
  select(bag:Bag){this.selected.set(bag);this.nextStatus='';this.motif='';this.message.set('');this.updateError.set('');}
  normal(before:Status,after:string){return after==='perdu'&&before!=='perdu'||['enregistre','trie','charge','en_vol'].includes(before)&&statuses[statuses.indexOf(before)+1]===after;}
  allowed(before:Status){return statuses.filter(s=>s!==before&&(this.auth.has('Superviseur')||this.normal(before,s)));}
  isAbnormal(before:Status){return !!this.nextStatus&&!this.normal(before,this.nextStatus);}
  async update(){const bag=this.selected();if(!bag||this.saving()||!this.nextStatus)return;this.saving.set(true);this.updateError.set('');this.message.set('');try{const result=await firstValueFrom(this.http.patch<{statut:Status}>(`/api/bagages/${bag.id}/statut`,{statut:this.nextStatus,motif:this.motif.trim()||null}));this.selected.set({...bag,statut:result.statut});this.nextStatus='';this.motif='';this.revision.update(x=>x+1);this.message.set('Statut enregistré. L’historique a été mis à jour.');await this.load();}catch(e){this.updateError.set(errorText(e));if((e as {status?:number}).status===409){await this.load();const fresh=this.bags().find(b=>b.id===bag.id);if(fresh)this.selected.set(fresh);this.revision.update(x=>x+1);}}finally{this.saving.set(false);}}
}
