import { Component, inject, signal } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { Flight, Bag, Agent, Role, roleLabels, errorText } from '../../shared/models';
import { Auth } from './auth';
import { BagHistory } from './history';

@Component({imports:[FormsModule,DatePipe],template:`
<div class="page-heading"><span class="eyebrow">PROGRAMME DES DÉPARTS</span><h1>Vols</h1><p class="muted">Les 100 derniers départs prévus, avec leurs horaires locaux.</p></div>
@if(error()){<div class="alert" role="alert">{{error()}}</div>}
<section class="panel"><div class="topline"><h2>Vols disponibles</h2><button class="btn secondary" (click)="load()" [disabled]="busy()">Actualiser</button></div>@if(busy()){<p role="status">Chargement…</p>}<div class="table-wrap"><table><thead><tr><th>Vol</th><th>Origine</th><th>Destination</th><th>Départ prévu</th></tr></thead><tbody>@for(v of flights();track v.id){<tr><td><strong>{{v.numero}}</strong></td><td>{{v.origine}}</td><td>{{v.destination}}</td><td>{{v.departPrevu | date:'dd/MM/yyyy à HH:mm'}}</td></tr>}</tbody></table></div>@if(!busy()&&!flights().length){<p class="empty">Aucun vol disponible. Un superviseur peut en créer un.</p>}</section>
@if(auth.has('Superviseur')){<section class="panel form-panel"><span class="eyebrow">SUPERVISION</span><h2 class="section-title">Créer un vol</h2><form #f="ngForm" class="stack" (ngSubmit)="create(f)"><div class="grid2"><div><label for="flight-number">Numéro du vol</label><input id="flight-number" name="numero" [(ngModel)]="numero" maxlength="12" required placeholder="Ex. TU701"></div><div><label for="departure">Départ prévu (heure locale)</label><input id="departure" name="depart" [(ngModel)]="depart" type="datetime-local" required></div></div><div class="grid2"><div><label for="origin">Origine · code IATA</label><input id="origin" name="origine" [(ngModel)]="origine" maxlength="3" pattern="[A-Za-z]{3}" required placeholder="TUN"></div><div><label for="destination">Destination · code IATA</label><input id="destination" name="destination" [(ngModel)]="destination" maxlength="3" pattern="[A-Za-z]{3}" required placeholder="CDG"></div></div>@if(message()){<div class="alert success" role="status">{{message()}}</div>}<button class="btn" [disabled]="saving()||f.invalid">{{saving()?'Création…':'Créer le vol'}}</button></form></section>}`})
export class FlightsPage {
  auth=inject(Auth);private http=inject(HttpClient);flights=signal<Flight[]>([]);busy=signal(false);saving=signal(false);error=signal('');message=signal('');numero='';origine='';destination='';depart='';
  constructor(){void this.load();}
  async load(){this.busy.set(true);this.error.set('');try{this.flights.set(await firstValueFrom(this.http.get<Flight[]>('/api/vols')));}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
  async create(form:NgForm){if(form.invalid||this.saving())return;this.saving.set(true);this.error.set('');this.message.set('');try{const date=new Date(this.depart);if(!Number.isFinite(date.getTime()))throw new Error();await firstValueFrom(this.http.post('/api/vols',{numero:this.numero,origine:this.origine.toUpperCase(),destination:this.destination.toUpperCase(),departPrevu:date.toISOString()}));form.resetForm();this.message.set('Le vol a été créé.');await this.load();}catch(e){this.error.set(errorText(e));}finally{this.saving.set(false);}}
}

@Component({imports:[FormsModule,DatePipe,BagHistory],template:`
<div class="page-heading"><span class="eyebrow">COMPTOIR D’ENREGISTREMENT</span><h1>Enregistrer un bagage</h1><p class="muted">Rattachez le bagage à son vol et remettez le code de suivi au passager.</p></div>
<section class="panel form-panel"><form #f="ngForm" class="stack" (ngSubmit)="create(f)"><div><label for="bag-flight">Vol de départ</label><select id="bag-flight" name="vol" [(ngModel)]="volId" required><option value="" disabled>Sélectionner un vol</option>@for(v of flights();track v.id){<option [value]="v.id">{{v.numero}} · {{v.origine}} → {{v.destination}} · {{v.departPrevu | date:'dd/MM HH:mm'}}</option>}</select>@if(!flights().length){<small class="muted">Aucun vol disponible. Contactez votre superviseur.</small>}</div><div class="grid2"><div><label for="passenger">Nom du passager</label><input id="passenger" name="passager" [(ngModel)]="nom" maxlength="150" autocomplete="off" required></div><div><label for="weight">Poids (kg)</label><input id="weight" name="poids" [(ngModel)]="poids" type="number" min="0.01" max="100" step="0.01" required></div></div><p class="muted small">L’identité du passager reste privée et n’apparaît pas dans le suivi public.</p><button class="btn" [disabled]="saving()||f.invalid||!flights().length">{{saving()?'Enregistrement…':'Enregistrer le bagage'}}</button></form>@if(error()){<div class="alert" role="alert">{{error()}}</div>}</section>
@if(created();as bag){<section class="panel receipt" aria-live="polite"><div class="topline"><h2>Bagage enregistré</h2><span class="badge">Enregistré</span></div><p>Code de suivi à remettre au passager :</p><p class="mono receipt-code">{{bag.trackingId}}</p><p class="muted small">Référence interne : <span class="mono">{{bag.id}}</span></p><p>{{bag.poidsKg}} kg · Conservez la référence interne pour consulter l’historique.</p></section><bag-history [bagId]="bag.id" />}
<section class="panel form-panel"><h2>Consulter un historique</h2><form (ngSubmit)="showHistory()" class="stack"><div><label for="history-id">Référence interne du bagage (UUID)</label><input id="history-id" name="historyId" [(ngModel)]="historyId" pattern="[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}" required></div><button class="btn secondary">Afficher l’historique</button></form></section>@if(history();as id){<bag-history [bagId]="id" />}`})
export class RegisterPage {
  private http=inject(HttpClient);flights=signal<Flight[]>([]);created=signal<Bag|null>(null);saving=signal(false);error=signal('');history=signal('');volId='';nom='';poids:number|null=null;historyId='';
  constructor(){void this.load();}
  async load(){try{this.flights.set(await firstValueFrom(this.http.get<Flight[]>('/api/vols')));}catch(e){this.error.set(errorText(e));}}
  showHistory(){if(/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(this.historyId))this.history.set(this.historyId);}
  async create(form:NgForm){if(form.invalid||this.saving())return;this.saving.set(true);this.error.set('');this.created.set(null);try{this.created.set(await firstValueFrom(this.http.post<Bag>('/api/bagages',{volId:this.volId,nomPassager:this.nom,poidsKg:this.poids})));this.nom='';this.poids=null;form.form.markAsPristine();}catch(e){this.error.set(errorText(e));}finally{this.saving.set(false);}}
}

@Component({imports:[FormsModule],template:`
<div class="page-heading"><span class="eyebrow">ADMINISTRATION SYSTÈME</span><h1>Comptes & rôles</h1><p class="muted">Attribuez à chaque membre de l’équipe les accès nécessaires à sa mission.</p></div>@if(error()){<div class="alert" role="alert">{{error()}}</div>}
<section class="panel"><div class="topline"><h2>Comptes de l’équipe</h2><button class="btn secondary" (click)="load()" [disabled]="busy()">Actualiser</button></div><p class="muted small">Les 100 premiers comptes, triés par identifiant.</p>@if(busy()){<p role="status">Chargement…</p>}<div class="table-wrap"><table><thead><tr><th>Identifiant</th><th>Rôle</th><th>État</th></tr></thead><tbody>@for(user of users();track user.id){<tr><td><strong>{{user.login}}</strong></td><td>{{labels[user.role]}}</td><td><span class="badge">{{user.actif?'Actif':'Désactivé'}}</span></td></tr>}</tbody></table></div></section>
<section class="panel form-panel"><h2>Créer un compte</h2><form #f="ngForm" class="stack" (ngSubmit)="create(f)"><div class="grid2"><div><label for="new-login">Identifiant du compte</label><input id="new-login" name="login" [(ngModel)]="login" maxlength="120" autocomplete="off" required></div><div><label for="new-role">Rôle</label><select id="new-role" name="role" [(ngModel)]="role" required>@for(r of roles;track r){<option [value]="r">{{labels[r]}}</option>}</select></div></div><div><label for="new-password">Mot de passe initial</label><input id="new-password" name="password" type="password" [(ngModel)]="password" minlength="12" maxlength="256" autocomplete="new-password" required><small class="muted">12 caractères minimum, avec majuscule, minuscule et chiffre.</small></div><p class="muted small">Le compte Administrateur gère les utilisateurs. Les opérations sur les vols et bagages nécessitent un compte métier distinct.</p>@if(message()){<div class="alert success" role="status">{{message()}}</div>}<button class="btn" [disabled]="saving()||f.invalid">{{saving()?'Création…':'Créer le compte'}}</button></form></section>`})
export class UsersPage {
  private http=inject(HttpClient);users=signal<Agent[]>([]);busy=signal(false);saving=signal(false);error=signal('');message=signal('');labels=roleLabels;roles=Object.keys(roleLabels) as Role[];login='';password='';role:Role='AgentEnregistrement';
  constructor(){void this.load();}
  async load(){this.busy.set(true);this.error.set('');try{this.users.set(await firstValueFrom(this.http.get<Agent[]>('/api/users')));}catch(e){this.error.set(errorText(e));}finally{this.busy.set(false);}}
  async create(form:NgForm){if(form.invalid||this.saving())return;this.saving.set(true);this.error.set('');this.message.set('');try{await firstValueFrom(this.http.post('/api/users',{login:this.login,password:this.password,role:this.role}));form.resetForm({role:'AgentEnregistrement'});this.password='';this.message.set('Compte créé. Transmettez les identifiants par un canal privé.');await this.load();}catch(e){this.error.set(errorText(e));}finally{this.saving.set(false);}}
}
